### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by JordanSussman** [target/go-arty#2]
## Integrations

- [x] Enable travis ci
- [x] Verify GoDoc results
- [x] Verify goreportcard results

## Communication

- [x] Update go-artifactory issue

**Comment by jbrockopp** [comment]
Travis CI has been setup and enabled https://travis-ci.org/target/go-arty

**Comment by jbrockopp** [comment]
GoDoc results:

https://godoc.org/github.com/target/go-arty/artifactory
https://godoc.org/github.com/target/go-arty/xray
