### ISSUE TITLE
storage.go: A File has a Size of type string and a FileListItem has a Size of type int

### ISSUE THREAD

**Issue by envasquez** [target/go-arty#23]
# Below are required fields for qualifying your issue to our support team

## Subject of the issue
storage.go: A File has a Size of type string and a FileListItem has a Size of type int

- [ ] Briefly describe your issue. More details can be added below.

## Your environment
- [ ] Artifactory version and/or Xray version
Artifactory version 2.0.0

- [ ] Golang version
go version go1.10.3 darwin/amd64
- [ ] Operating System
Mac OS X: Mojave

- [ ] Database type/version (if relevant)
N/A

## Expected behavior
Consistent structure types

- [ ] Tell us what should happen
Both a File and FileListItem should represent size as an int.

## Actual behavior
Ints and strings have to be handled differently/converted

- [ ] Tell us what happens instead, including any relevant errors or stack trace
N/A
- [ ] Verify you have redacted any sensitive hostnames, credentials, application names, etc from these errors/stack traces
N/A

## Steps to Reproduce
1. See Line 72 of storage.go
2. See Line 170 of storage.go

**Comment by jbrockopp** [comment]
After performing some testing, it seems that the Artifactory API itself returns the size as a string.

So this actually isn't a bug but rather intended functionality.

I'll wait to close this issue in case there is anymore questions/comments/concerns, but I will be closing the PR now.
