### ISSUE TITLE
Rename BypassHeadRequest to BypassHeadRequests on RemoteRepository struct

### ISSUE THREAD

**Issue by joeh90** [target/go-arty#36]
# Below are required fields for qualifying your issue to our support team

## Subject of the issue

- [ ] BypassHeadRequests field is incorrectly named BypassHeadRequest in RemoteRepository struct

## Your environment

- [ ] Artifactory 6.15.0

## Expected behavior

- [ ] Should be able to set BypassHeadRequests field

## Actual behavior

- [ ] Unable to set BypassHeadRequests field as it is incorrectly named BypassHeadRequest in RemoteRepository struct

## Steps to Reproduce

N/A

**Comment by JordanSussman** [comment]
Closed via #40. Thanks for the contributions!
