### ISSUE TITLE
Add missing NuGet fields to RemoteRepository struct

### ISSUE THREAD

**Issue by joeh90** [target/go-arty#37]
# Below are required fields for qualifying your issue to our support team

## Subject of the issue

- [ ] Add missing NuGet fields to RemoteRepository struct

## Your environment

- [ ] Artifactory 6.15.0

## Expected behavior

- [ ] Should be able to set NuGet remote repository fields
- [ ] feedContextPath *string
- [ ] downloadContextPath *string
- [ ] v3FeedUrl *string

## Actual behavior

- [ ] Unable to currently set NuGet remote repository fields: feedContextPath, downloadContextPath, v3FeedUrl

## Steps to Reproduce

N/A

**Comment by JordanSussman** [comment]
Closed via #40. Thanks for the contributions!
